### ISSUE TITLE
Problème avec les fichiers en markdown

### ISSUE THREAD

**Issue by davidbgk** [sudweb/frank#20]
J'ai l'impression que seul le formatage qui est proposé en premier dans la Notice permet une récupération des contenus lors de la construction du site. Tous les témoignages utilisant le markdown (`##`) ne sont pas pris en compte. Je ne suis pas assez familier de Jekyll pour savoir comment activer cette option facilement.

Je peux faire une PR pour corriger la Notice et uniformiser les contenus par contre.

**Comment by wo0dyn** [comment]
La syntaxe _alternative_ a été supprimée dans 967cb36ddb5c7ecbd395c8c35ef3aa3f5609d176. 😊
